import type { Config, DOMPurify } from 'dompurify';

export const markdownSanitizeConfig: Config = {
  ALLOWED_TAGS: [
    'a',
    'blockquote',
    'br',
    'code',
    'div',
    'em',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'li',
    'ol',
    'p',
    'pre',
    's',
    'span',
    'strong',
    'table',
    'tbody',
    'td',
    'th',
    'thead',
    'tr',
    'ul',
  ],
  ALLOWED_ATTR: [
    'class',
    'href',
    'rel',
    'target',
    'title',
  ],
  ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|tel):|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i,
  FORBID_ATTR: ['style'],
  FORBID_TAGS: [
    'button',
    'embed',
    'form',
    'iframe',
    'input',
    'math',
    'object',
    'script',
    'select',
    'style',
    'svg',
    'textarea',
  ],
};

export const sanitizeMarkdownHtml = (
  purifier: DOMPurify,
  html: string
): string => purifier.sanitize(html, markdownSanitizeConfig);
